:hivemq-support: http://www.hivemq.com/support/

== HiveMQ Deny Wildcard Subscription Extension
*Extension Type*: Security

*Version*: 4.1.1

*License*: Apache License 2.0

=== Purpose

This extension denies any subscription to the root wildcard topic. In general, root wildcard subscribers tend to be a bottleneck in many scenarios.

=== Installation
. Unzip the downloaded zip file
. Copy the folder `hivemq-deny-wildcard-extension` to your `[HIVEMQ_HOME]/extensions` folder
. Done

=== Configuration

No configuration needed, works out of the box.

=== First Steps
After the extension is installed start HiveMQ. Now no client is allowed to subscribe to `#`, `+/#`, `$share/group/#`
or any other topic filter that would represent a root wildcard.

==== Need help?

If you encounter any problems, we are happy to help. The best place to get in contact is our {hivemq-support}[support^].

= Contributing

If you want to contribute to HiveMQ Deny Wildcard Extension, see the link:CONTRIBUTING.md[contribution guidelines].

= License

HiveMQ Deny Wildcard Extension is licensed under the `APACHE LICENSE, VERSION 2.0`. A copy of the license can be found link:LICENSE.txt[here].

