[versions]
commonsLang = "3.12.0"
hivemq-extensionSdk = "4.1.0"
junit-jupiter = "5.9.1"
mockito = "4.8.0"

[libraries]
commonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[plugins]
hivemq-extension = { id = "com.hivemq.extension", version = "3.1.0" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
asciidoctor = { id = "org.asciidoctor.jvm.convert", version = "3.3.2" }
